### ISSUE TITLE
The name of language in a function gets quoted in the SQL tab (RM #3592)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2037]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3592***
*Originally created by **André Gracioso Peres da Silva** at 2018-08-27 13:53:31 UTC.*

When specifying the name of a language in a function, for example:

    ...
    LANGUAGE plpgsql
    ...

the SQL tab will show it with quotes. Example:

    ...
    LANGUAGE 'plpgsql'
    ...

Is this by design? I thought the correct way to write it was without the quotes. See here:

https://stackoverflow.com/questions/12514664/postgresql-procedural-language-c-not-found/12530268#12530268

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by brsa** [comment]
> Using quotes is fine, ...

No, it is not fine. This has been deprecated for a very long time now.

Up to Postgres 9.3, [the manual](https://www.postgresql.org/docs/9.3/sql-createfunction.html#AEN71172) advises:

> For backward compatibility, the name can be enclosed by single quotes.

Since Postgres 9.4 up to the [current version](https://www.postgresql.org/docs/current/sql-createfunction.html#id-1.9.3.67.6) (Postgres 15 at the time of writing) it has been:

> Enclosing the name in single quotes is deprecated and requires matching case.

Rightly deprecated. The language name is an identifier and should not be single-quoted. I would appreciate if you could fix it, as it confuses people.
