### ISSUE TITLE
Option to disable load animation (brakes Remote Desktop) (RM #6349)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4244]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6349***
*Originally created by **Maciej Nux** at 2021-03-26 09:38:28 UTC.*

Animations are a problem for Remote Desktop (and a bit for VNC, but I guess less prominent). This is a big problem for me during pandemic.

It looks like the pgAdmin is slow, but it is not. Sometimes it even seems like it is loading endlessly. Minimizing the window and showing it helps. So you see -- this is a refresh problem. Because of the animation.

Also note that disabling browser tree animation helps a lot in Remote Desktop. So it would be great if there would be an option to disable load animation :-). Or even better -- a combo-checked (checkbox for a group) that would disable all animations.

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by Eccenux** [comment]
Fixed in pgAdmin version 6.0. The problem was more general than I thought. The window did not refresh properly and the password prompt was not visible. This artificially lengthened the loading of the window. When I moved the pane, the prompt popped up.

With the remote connection, the problem was more apparent to me, but it turned out to be similar without the remote connection.

Anyway, just wanted to say it's fixed, thanks ;-)
